# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\"7\n\x1fGetLoginVerificationCodeRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\"\"\n GetLoginVerificationCodeResponse\"b\n\x0cLoginRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x19\n\x11verification_code\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\"7\n\rLoginResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x15\n\rauthorization\x18\x02 \x01(\t\"8\n\x0eLoginV2Request\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\x0fLoginV2Response\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x15\n\rauthorization\x18\x02 \x01(\t\"\x18\n\x16LoginByOneClickRequest\"A\n\x17LoginByOneClickResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x15\n\rauthorization\x18\x02 \x01(\t\"\x83\x02\n\x11MyProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t\x12\x0f\n\x07steamid\x18\x04 \x01(\t\x12\x15\n\rregister_time\x18\x05 \x01(\x03\x12 \n\x07members\x18\x06 \x03(\x0b\x32\x0f.account.Member\x12\x1f\n\x06member\x18\x07 \x01(\x0b\x32\x0f.account.Member\x12,\n\x0bvideo_award\x18\x08 \x01(\x0b\x32\x17.account.UserVideoAward\x12\"\n\x1amobile_not_get_ad_duration\x18\t \x01(\x03\"+\n\x06Member\x12\x0c\n\x04type\x18\x01 \x01(\x03\x12\x13\n\x0b\x65xpire_time\x18\x02 \x01(\x03\",\n\x0eUserVideoAward\x12\r\n\x05\x61ward\x18\x01 \x01(\x03\x12\x0b\n\x03has\x18\x02 \x01(\x08\"\x15\n\x13RefreshTokenRequest\"-\n\x14RefreshTokenResponse\x12\x15\n\rauthorization\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLOGINVERIFICATIONCODEREQUEST']._serialized_start=26
  _globals['_GETLOGINVERIFICATIONCODEREQUEST']._serialized_end=81
  _globals['_GETLOGINVERIFICATIONCODERESPONSE']._serialized_start=83
  _globals['_GETLOGINVERIFICATIONCODERESPONSE']._serialized_end=117
  _globals['_LOGINREQUEST']._serialized_start=119
  _globals['_LOGINREQUEST']._serialized_end=217
  _globals['_LOGINRESPONSE']._serialized_start=219
  _globals['_LOGINRESPONSE']._serialized_end=274
  _globals['_LOGINV2REQUEST']._serialized_start=276
  _globals['_LOGINV2REQUEST']._serialized_end=332
  _globals['_LOGINV2RESPONSE']._serialized_start=334
  _globals['_LOGINV2RESPONSE']._serialized_end=391
  _globals['_LOGINBYONECLICKREQUEST']._serialized_start=393
  _globals['_LOGINBYONECLICKREQUEST']._serialized_end=417
  _globals['_LOGINBYONECLICKRESPONSE']._serialized_start=419
  _globals['_LOGINBYONECLICKRESPONSE']._serialized_end=484
  _globals['_MYPROFILERESPONSE']._serialized_start=487
  _globals['_MYPROFILERESPONSE']._serialized_end=746
  _globals['_MEMBER']._serialized_start=748
  _globals['_MEMBER']._serialized_end=791
  _globals['_USERVIDEOAWARD']._serialized_start=793
  _globals['_USERVIDEOAWARD']._serialized_end=837
  _globals['_REFRESHTOKENREQUEST']._serialized_start=839
  _globals['_REFRESHTOKENREQUEST']._serialized_end=860
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=862
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
